package subscription

import (
	"context"

	"github.com/ddelizia/hasura-saas/pkg/gqlsdk"
	"github.com/sirupsen/logrus"
	"github.com/stripe/stripe-go"
)

// Autogenerated by ./cmd/stripe_event_code_generator/main.go

func EventMapping(c context.Context, event stripe.Event, id string, sdkSvc gqlsdk.Service) {
	switch event.Type {

	case "charge.succeeded":
		ProcessChargeSucceeded(event, id)
	case "customer.created":
		ProcessCustomerCreated(event, id)
	case "customer.subscription.created":
		ProcessCustomerSubscriptionCreated(event, id)
	case "customer.subscription.deleted":
		ProcessCustomerSubscriptionDeleted(event, id)
	case "customer.updated":
		ProcessCustomerUpdated(event, id)
	case "invoice.created":
		ProcessInvoiceCreated(event, id)
	case "invoice.finalized":
		ProcessInvoiceFinalized(event, id)
	case "invoice.paid":
		ProcessInvoicePaid(event, id)
	case "invoice.payment_action_required":
		ProcessInvoicePaymentActionRequired(event, id)
	case "invoice.payment_failed":
		ProcessInvoicePaymentFailed(c, event, id, sdkSvc)
	case "invoice.payment_succeeded":
		ProcessInvoicePaymentSucceeded(event, id)
	case "payment_intent.created":
		ProcessPaymentIntentCreated(event, id)
	case "payment_intent.requires_action":
		ProcessPaymentIntentRequiresAction(event, id)
	case "payment_intent.succeeded":
		ProcessPaymentIntentSucceeded(event, id)
	case "payment_method.attached":
		ProcessPaymentMethodAttached(event, id)

	default:
		// unhandled event type
		logrus.WithField("eventType", event.Type).Warn("event not mapped")
	}
}
