env:
  mock:
    data: some value
http:
  headerNames:
    jwt: Authorization
    accountId: X-Account-Id
subastas:
  colly:
    storage: "/tmp/colly_storage.db"
  index:
    public: public
    private: private
authz:
  oidc:
    jwks:
      url: "https://something.eu.auth0.com/.well-known/jwks.json"
    headerNames:
      dcodedJwt: X-Hasura-Saas-Decoded-Jwt
  users:
    anonymous: anonymous
  roles:
    anonymous: anonymous
    accountOwner: account_owner
    loggedIn: logger_in
  accounts:
    anonymous: anonymous
graphql:
  url: "http://localhost:8082/v1/graphql"
  hasura:
    adminSecret: myadminsecretkey
    headerNames:
      userId: X-Hasura-User-Id
      accountId: X-Hasura-Account-Id
      role: X-Hasura-Role
logger:
  level: debug
rp:
  server:
    listenAddress: ":1340"
  es:
    url: "http://localhost:9200"
    index:
      public: /public/
      private: /private/
    headerNames:
      authorization: X-Es-Authorization
  graphql:
    url: "http://localhost:8082/v1/graphql"
    hasura:
hshttp:
  headerNames:
    accountId: "X-Account-Id"
    jwt: "Authorization"
subscription:
  server:
    listenAddress: ":1340"
  stripe:
    webhookSecret: whsec_xxx
    domain: yyyy
    apiKey: sk_test_xxxx
saas:
  server:
    listenAddress: ":1340"
email:
  from: "some@email.com"
  sendgrid:
    apiKey: "xxxx"
