version: '3.6'
services:
  
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  graphql-engine:
    image: hasura/graphql-engine:v2.0.6.cli-migrations-v3
    ports:
    - "8082:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "inherited_roles"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 15
      SAAS_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      MICRO_SUBSCRIPTIONS_BASE_URL: "http://hs-subscription:1340"
      HASURA_GRAPHQL_MIGRATIONS_DIR: /data/hasura/migrations
      HASURA_GRAPHQL_METADATA_DIR: /data/hasura/metadata
    volumes:
    - ./hasura:/data/hasura

  hs-subscription:
    image: golang:1.16
    working_dir: /app
    depends_on: 
    - graphql-engine
    volumes:
    - ./go.mod:/app/go.mod:ro
    - ./go.sum:/app/go.sum:ro
    - ./config.yaml:/app/config.yaml:ro
    - ./cmd/:/app/cmd/:ro
    - ./pkg/:/app/pkg/:ro
    environment: 
      SUBSCRIPTION.STRIPE.APIKEY: ${STRIPE_KEY}
      SUBSCRIPTION.STRIPE.WEBHOOKSECRET: ${STRIPE_WEBHOOK_SECRET}
      GRAPHQL.HASURA.ADMINSECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      GRAPHQL.URL: "http://graphql-engine:8080/v1/graphql"
      LOGGER.LEVEL: "debug"
    expose: 
    - "1340"
    ports: 
    - "1341:1340"
    command: 
    - "go"
    - "run"
    - "./cmd/subscription/main.go"

  hs-rp:
    image: golang:1.16
    depends_on: 
    - graphql-engine
    working_dir: /app
    volumes:
    - ./go.mod:/app/go.mod:ro
    - ./go.sum:/app/go.sum:ro
    - ./config.yaml:/app/config.yaml:ro
    - ./cmd/:/app/cmd/:ro
    - ./pkg/:/app/pkg/:ro
    environment: 
      GRAPHQL.HASURA.ADMINSECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      GRAPHQL.URL: "http://graphql-engine:8080/v1/graphql"
      LOGGER.LEVEL: "debug"
    expose: 
    - "1340"
    ports: 
    - "1342:1340"
    command: 
    - "go"
    - "run"
    - "./cmd/rp/main.go"
  
  hs-saas:
    image: golang:1.16
    depends_on: 
    - graphql-engine
    working_dir: /app
    volumes:
    - ./go.mod:/app/go.mod:ro
    - ./go.sum:/app/go.sum:ro
    - ./config.yaml:/app/config.yaml:ro
    - ./cmd/:/app/cmd/:ro
    - ./pkg/:/app/pkg/:ro
    environment: 
      GRAPHQL.HASURA.ADMINSECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      GRAPHQL.URL: "http://graphql-engine:8080/v1/graphql"
      LOGGER.LEVEL: "debug"
    expose: 
    - "1340"
    ports: 
    - "1343:1340"
    command: 
    - "go"
    - "run"
    - "./cmd/saas/main.go"

  stripe-cli:
    image: stripe/stripe-cli
    depends_on: 
    - hs-subscription
    environment: 
      STRIPE_API_KEY: ${STRIPE_KEY}
    entrypoint:
    - "/bin/stripe" 
    - "listen"
    - "--forward-to"
    - "hs-subscription:1340/webhook"
    - "--latest"

volumes:
  db_data:

