package model

const (
	STATUS_INIT = "init"

	LOG_PARAM_INVOICE_ID      = "INVOICE_ID"
	LOG_PARAM_SUBSCRIPTION_ID = "SUBSCRIPTION_ID"
	LOG_PARAM_CUSTOMER_ID     = "CUSTOMER_ID"
	LOG_PARAM_PLAN_ID         = "PLAN_ID"
	LOG_PARAM_STRIPE_RESPONSE = "STRIPE_RESPONSE"
	LOG_PARAM_STRIPE_PLAN_ID  = "STRIPE_PLAN_ID"
	LOG_PARAM_HASURA_RESPONSE = "HASURA_RESPONSE"
	LOG_PARAM_ACCOUNT_NAME    = "ACCOUNT_NAME"
	LOG_PARAM_ACCOUNT_ID      = "ACCOUNT_ID"
	LOG_PARAM_USER_ID         = "USER_ID"
	LOG_PARAM_RESULT_LENGTH   = "RESULT_LENGTH"
)
