name: Release Build
on:
  push:
    tags:
      - v*
    paths-ignore:
      - '**.md'

env:
  REGISTRY: ghcr.io
  HASURA_SCHEMA_FOLDER: "./hasura-saas-schema"

jobs:

  docker:
    name: Create docker image and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true
    
    - name: Build docker images
      run: ./scripts/docker-build.sh $GITHUB_SHA

    - name: Log docker images
      run: ./scripts/docker-push.sh $GITHUB_SHA ${GITHUB_REF#refs/tags/}

    - name: Build hasura
      run: |
        (cd hasura/metadata && zip -r metadata.zip .)
        (cd hasura/migrations && zip -r migrations.zip .)

    - name: Upload Release Asset Metadata
      id: upload-release-asset-metadata
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.HASURA_SCHEMA_FOLDER }}/metadata/metadata.zip
        asset_name: metadata.zip
        asset_content_type: application/zip
    
    - name: Upload Release Asset Migrations
      id: upload-release-asset-migrations
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.HASURA_SCHEMA_FOLDER }}/migrations/migrations.zip
        asset_name: migrations.zip
        asset_content_type: application/zip

  go-list:
    name: Create go package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.5'
    
    - name: List go package
      run: ./scripts/go-list.sh ${GITHUB_REF#refs/tags/}

